### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by asakura42** [singalhimanshu/taskgo#1]
Great kanban, thank you for your work! Except for the lack of tags, it would be very convenient to sort university shit by different tags for example.

**Comment by singalhimanshu** [comment]
> Great kanban, thank you for your work!
Thanks! 
> Except for the lack of tags, it would be very convenient to sort university shit by different tags for example.
Sure I'll put it on the features list.

**Comment by singalhimanshu** [comment]
This feature will take some time so I created a new branch [tags-feature](https://github.com/singalhimanshu/taskgo/tree/tags-feature).

**Comment by singalhimanshu** [comment]
Sorry for taking a lot of time. But I think there is some limitations in terminal to implement this functionality effectively. For now I'm closing this issue but you can check #9 which will provide a better functionality to separate the boards (in my opinion).
