### ISSUE TITLE
Сustom files support

### ISSUE THREAD

**Issue by asakura42** [singalhimanshu/taskgo#2]
It would be great if the program would read custom files from, for example, arguments.

Such black magic may well work:

`var fileName = "/" + os.Args[1]` instead `const fileName = "/taskgo.md"`

**Comment by singalhimanshu** [comment]
Sure this will be an easy one to do. Would you like to make a PR? Let me know.

**Comment by asakura42** [comment]
I know very little about Go, but I can try. Anyway the idea is simple: if there are no arguments, read the default `taskgo.md`, otherwise read `os.Args[1]`.

**Comment by singalhimanshu** [comment]
> I know very little about Go, but I can try. Anyway the idea is simple: if there are no arguments, read the default `taskgo.md`, otherwise read `os.Args[1]`.

Sure let me know if you need some help.

**Comment by singalhimanshu** [comment]
Added in 467343b92f1b18f7f1dcd7aa86bd84414c642116. Let me know if it works well or are there any problems. Closing it for now.
